# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
