# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppin', '0004_auto_20170911_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
