# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poppin', '0005_auto_20170920_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='content',
            field=models.CharField(default='', max_length=9000000),
        ),
    ]
