# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelgaming', '0002_auto_20171220_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=5000000000000)),
                ('username', models.TextField(default='', max_length=60000000)),
                ('description', models.TextField(default='', max_length=60000000)),
                ('title', models.TextField(default='', max_length=60000000)),
            ],
        ),
    ]
