# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelgaming', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 7, 58, 8, 506251)),
        ),
    ]
